 github: [metadata]
 encoding: UTF-8
 name: Alisa in Tech
 description: I write about being in tech
 url: https://www.alisa-in.tech/
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-minimal
 gfm_quirks: paragraph_end